CREATE TABLE T_PERSON(
    PK_ID		VARCHAR(36) NOT NULL,
    PV_NAME		VARCHAR(32) NOT NULL,
    PRIMARY KEY (PK_ID)
);
CREATE TABLE T_BOOK(
    PK_ID		VARCHAR(36) NOT NULL,
    FK_AUTHOR	VARCHAR(36) NOT NULL,
    PV_NAME		VARCHAR(255) NOT NULL,
    PRIMARY KEY (PK_ID),
    FOREIGN KEY (FK_AUTHOR) REFERENCES T_PERSON (PK_ID)
);
CREATE TABLE T_LINK(
    PK_ID      VARCHAR(36) NOT NULL,
    FK_PERSON  VARCHAR(36) NOT NULL,
    FK_BOOK    VARCHAR(36) NOT NULL,
    PRIMARY KEY (PK_ID),
    FOREIGN KEY (FK_PERSON) REFERENCES T_PERSON (PK_ID),
    FOREIGN KEY (FK_BOOK) REFERENCES T_BOOK (PK_ID)
);